name: IT

on:
  - push
  - workflow_dispatch

jobs:
  it:
    runs-on: ubuntu-latest

    container: ubuntu:22.04
    services:
      lila:
        image: ghcr.io/lichess-org/lila-docker:ci
        options: --restart=always

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          path: chariot

      - name: Install curl
        run: apt-get update && apt-get install -y curl

      - name: Download OpenJDK 21
        run: |
          download_url="https://download.java.net/java/GA/jdk21.0.2/f2283984656d49d69e91c558476027ac/13/GPL/openjdk-21.0.2_linux-x64_bin.tar.gz"
          curl -Lo $RUNNER_TEMP/java_package.tar.gz $download_url

      - uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '21'
          architecture: x64

      - name: Check java version
        run: java -Xinternalversion

      - name: Run integration tests
        run: chariot/build/integration/run-tests.sh
